version: '3.8'
services:
  app:
    container_name: API_conexa
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb_conexa

  mongodb_conexa:
    image: mongo
    container_name: mongodb_conexa
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/database:/data/db