version: '3.8'
services:
  app:
    container_name: API
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/database:/data/db